swagger: '2.0'
info:
  title: HelloWorldAPI
  description: Sample API with Google Cloud Functions Backend
  version: '1.0'
# basePath: /v1
# host: api.server.test
schemes:
  - https
produces:
  - application/json
security:
  - api_key: [] # everybody has to authenticate using an API Key

paths:
  /helloworld:
    get:
      summary: Just outputs Hello world
      operationId: helloWorld
      x-google-backend:
        address: "https://europe-west1-cloudintroduction-420521.cloudfunctions.net/helloworldfunction" # important for every backend service
      responses:
        200:
          description: OK
